name: Continuous Deployment TEST

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "my-spring-boot-app"
      DOCKER_REGISTRY: "docker.io"
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn package --no-transfer-progress

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v1
        with:
          args: set image deployment/${{ env.APP_NAME }} ${{ env.APP_NAME }}=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
