name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Unit Tests
        run: mvn clean package
      - name: Rename the artifact
        run: cp target/notes-jwt-1.0-SNAPSHOT.jar notes-jwt-${{ github.sha }}.jar
      - name: Save the artifact
        uses: actions/upload-artifact@v2
        with:
          name: notes-jwt
          path: notes-jwt-${{ github.sha }}.jar

fake-deploy:
  runs-on: ubuntu-latest
  needs: run-unit-tests
  steps:
    - name: Download the artifact
      uses: actions/download-artifact@v2
      with:
        name: notes-jwt

    - name: Fake deploy
      run: ls notes-jwt*.jar