name: Continuous Deployment TEST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "notes-jwt"
      DOCKER_REGISTRY: "docker.io"
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package --no-transfer-progress

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Deploy to Kubernetes
        uses: gane5hvarma/kubectl-actions@master
        with:
          args: set image deployment/${{ env.APP_NAME }} ${{ env.APP_NAME }}=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
